apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-udev-video
spec:
  protocol:
    udev:
      udevRules:
      - KERNEL=="video[0-1]*"
  brokerPodSpec:
    containers:
    - name: akri-udev-video-broker
      image: "ghcr.io/deislabs/akri/udev-video-broker"
      imagePullPolicy: Always
      env:
        - name: FORMAT
          value: "JPEG"
        - name: FRAMES_PER_SECOND
          value: "30"
        - name: RESOLUTION_HEIGHT
          value: "800"
        - name: RESOLUTION_WIDTH
          value: "1000"
      securityContext:
        privileged: true
      resources:
        limits:
          "{{PLACEHOLDER}}" : "1"
  instanceServiceSpec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8083
  configurationServiceSpec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8083
  properties: {}
  capacity: 2
